# New Project Example
#
# Project configuration file

apiVersion: 1

# Name of your project
name: "Customer Segmentation"

# Add integrations to your project. Credentials for these integrations is saved in
# Layer Cloud.
integrations:
  # Name of the integration.
  # You will be referring to this integration with this unique name
  layer:
    type: snowflake
